library(data.table)
library(ggplot2)
library(reshape)
library(httr)
library(jsonlite)
library(RSocrata)
## Not working... crimedataset <- read.socrata('https://data.cityofchicago.org/resource/ijzp-q8t2')
Crimes_._2001_to_present <- read.csv("~/Dropbox/00 R/CityLab/Crimes_-_2001_to_present.csv")
View(Crimes_._2001_to_present)
dt <- as.Date(posixify(crimedb$Date))
sum.by.type <- summary(crimedb$Primary.Type, Index=crimedb$Primary.Type)
table(crimedb$Year, crimedb$Primary.Type=="BURGLARY")
table(crimedb$Year, crimedb$Primary.Type=="BATTERY")
table(crimedb$Community.Area, crimedb$Primary.Type=="BURGLARY")
table(crimedb$Community.Area, crimedb$Primary.Type=="BATTERY")