library(data.table)
library(ggplot2)
library(reshape)
library(httr)
library(jsonlite)
library(RSocrata)
help(plyr)
example(ddply)
## Not working... crimedataset <- read.socrata('https://data.cityofchicago.org/resource/ijzp-q8t2')
Crimes_._2001_to_present <- read.csv("~/Dropbox/00 R/CityLab/Crimes_-_2001_to_present.csv")
View(Crimes_._2001_to_present)
help(as.Date)
dt <- as.Date(posixify(crimedb$Date))
str(dt) #To understand the structure of dates
# fix(dt) #Ro see how the data looks. You can change the values. It is like edit in Stata
# discharge(dt) #
month <- as.numeric(dt, %m)
day <- as.numeric(dt, %d)
sum.by.type <- summary(crimedb$Primary.Type, Index=crimedb$Primary.Type)
table(crimedb$Year, crimedb$Primary.Type=="BURGLARY")
table(crimedb$Year, crimedb$Primary.Type=="BATTERY")
table(crimedb$Community.Area, crimedb$Primary.Type=="BURGLARY")
table(crimedb$Community.Area, crimedb$Primary.Type=="BATTERY")
plot(crimedb$Community.Area, crimedb$Primary.Type=="BURGLARY")
select(crimedb$Community.Area, crimedb$Primary.Type=="BATTERY")

View(dt)